### ISSUE TITLE
project.jobs close_reason support needed

### ISSUE THREAD

**Issue by stav** [scrapinghub/python-scrapinghub#11] opened 2013-06-20 21:23 UTC
I would like to get the last "finished" job for a spider.

But if I do:

```
project.jobs(spider='myspider', state='finished', count=-1)
```

I will only get jobs with a _state_ of `finished` but this may include jobs with a _close_reason_ of `shutdown` or something other than "finished".

I would like to be able to do:

```
project.jobs(spider='myspider', close_reason='finished', count=-1)
```

which would of course assume that _state_ is `finished` as well.

**Comment by elacuesta** [comment] 2018-01-06 01:13
My good friend @stav, I think the problem is that the `close_reason` lookup is not supported by the HTTP backend (at least it's not mentioned in https://doc.scrapinghub.com/api/jobs.html#jobs-list-json-jl
I know, I'm a bit late to the party, but just in case ;-)

**Comment by vshlapakov** [comment] 2018-01-15 15:04
While @ip1981 is right indeed and it could be done via 2 steps, I don't see any harm in adding an additional `close_reason` filter for jobs in `finished` state, it's not a must indeed but can be pretty useful in some cases. @dangra do you agree? If not, let's just close the issue, it's shame it's here for such a long time.

**Comment by dangra** [comment] 2018-01-15 18:22
I think the problem is that server side it will require a non-efficient scan on finished jobs. Although this is still more efficient than filtering client side, it is not as straightforward as we wish.

**Comment by dangra** [comment] 2018-01-16 13:02
I think it is going to be client side filtering then.

**Closed by dangra** 2018-01-16 13:02 UTC
